### ISSUE TITLE
How to reproduce the results?

### ISSUE THREAD

**Issue by JunzheShen** [RUCAIBox/R1-Searcher#4]
Hi, could you please provide detailed guides to run the evaluation? e.g. environment requirements, data preparation, model preparation etc.?

**Comment by SsmallSong** [comment]
I have updated Quick Start. You can check it to reproduce our results. If you have any difficulties, please continue to contact me!

**Comment by JunzheShen** [comment]
> I have updated Quick Start. You can check it to reproduce our results. If you have any difficulties, please continue to contact me!

Hi, I'm curious why the input file name in `split_kilt_to_100.py` is not `kilt_knowledgesource.json`?  Are there any other steps required?

**Comment by JunzheShen** [comment]
> I have updated Quick Start. You can check it to reproduce our results. If you have any difficulties, please continue to contact me!

It seems that you are splitting the pickle file of embeddings. But the code in `wiki_corpus_index_bulid/build_corpus_embedding.py` does not seem to store the embeddings in separate files

**Comment by SsmallSong** [comment]
> > I have updated Quick Start. You can check it to reproduce our results. If you have any difficulties, please continue to contact me!
> 
> Hi, I'm curious why the input file name in `split_kilt_to_100.py` is not `kilt_knowledgesource.json`? Are there any other steps required?

Hello, there is no necessary additional operation here. The additional operation I perform is to filter out unnecessary key attributes in the original json file. This can reduce the memory occupied by the file.

**Comment by SsmallSong** [comment]
> > I have updated Quick Start. You can check it to reproduce our results. If you have any difficulties, please continue to contact me!
> 
> It seems that you are splitting the pickle file of embeddings. But the code in `wiki_corpus_index_bulid/build_corpus_embedding.py` does not seem to store the embeddings in separate files

You can write a simple script to process the split files separately. The significance of doing this is only to accelerate the embedding process.

**Comment by SsmallSong** [comment]
> > > I have updated Quick Start. You can check it to reproduce our results. If you have any difficulties, please continue to contact me!
> > 
> > 
> > Hi, I'm curious why the input file name in `split_kilt_to_100.py` is not `kilt_knowledgesource.json`? Are there any other steps required?
> 
> Hello, there is no necessary additional operation here. The additional operation I perform is to filter out unnecessary key attributes in the original json file. This can reduce the memory occupied by the file.

I have released the samples of the data we used. They can be found here: https://github.com/RUCAIBox/R1-Searcher/tree/main/wiki_corpus_index_bulid/samples.

**Comment by lebronjamesking** [comment]
Job submission server address: http://127.0.0.1:73

-------------------------------------------------------
Job 'raysubmit_umkfDvXiVAeCp2bS' submitted successfully
-------------------------------------------------------

Next steps
  Query the logs of the job:
    ray job logs raysubmit_umkfDvXiVAeCp2bS
  Query the status of the job:
    ray job status raysubmit_umkfDvXiVAeCp2bS
  Request the job to be stopped:
    ray job stop raysubmit_umkfDvXiVAeCp2bS

Tailing logs until the job exits (disable with --no-wait):
2025-03-18 11:56:22,058 INFO job_manager.py:530 -- Runtime env is setting up.
[2025-03-18 11:56:35,960] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2025-03-18 11:56:39,924 INFO worker.py:1514 -- Using address 10.35.16.135:72 set in the environment variable RAY_ADDRESS
2025-03-18 11:56:39,925 INFO worker.py:1654 -- Connecting to existing Ray cluster at address: 10.35.16.135:72...
2025-03-18 11:56:39,935 INFO worker.py:1832 -- Connected to Ray cluster. View the dashboard at 127.0.0.1:73 

From the message above, I am seeing that the process is not continue. It stucks or suspend or hang somewhere. Any ideas how to solve this problem

**Comment by lebronjamesking** [comment]
> > > > I have updated Quick Start. You can check it to reproduce our results. If you have any difficulties, please continue to contact me!
> > > 
> > > 
> > > Hi, I'm curious why the input file name in `split_kilt_to_100.py` is not `kilt_knowledgesource.json`? Are there any other steps required?
> > 
> > 
> > Hello, there is no necessary additional operation here. The additional operation I perform is to filter out unnecessary key attributes in the original json file. This can reduce the memory occupied by the file.
> 
> I have released the samples of the data we used. They can be found here: https://github.com/RUCAIBox/R1-Searcher/tree/main/wiki_corpus_index_bulid/samples.

A quick question, when I doing the stage 2 on qwen2.5-3B, the stage2.jsonl input_key is question, but get_reward() function call returns keyerror since there is no question retrieved. If I use apply_chat_template does not resolve the problem. Many thanks~

**Comment by lebronjamesking** [comment]
> > > > > I have updated Quick Start. You can check it to reproduce our results. If you have any difficulties, please continue to contact me!
> > > > 
> > > > 
> > > > Hi, I'm curious why the input file name in `split_kilt_to_100.py` is not `kilt_knowledgesource.json`? Are there any other steps required?
> > > 
> > > 
> > > Hello, there is no necessary additional operation here. The additional operation I perform is to filter out unnecessary key attributes in the original json file. This can reduce the memory occupied by the file.
> > 
> > 
> > I have released the samples of the data we used. They can be found here: https://github.com/RUCAIBox/R1-Searcher/tree/main/wiki_corpus_index_bulid/samples.
> 
> A quick question, when I doing the stage 2 on qwen2.5-3B, the stage2.jsonl input_key is question, but get_reward() function call returns keyerror since there is no question retrieved. If I use apply_chat_template does not resolve the problem. Many thanks~

Below is the detailed information attached from the code:

<|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
Where was the place of burial of the director of film Young Dr. Kildare?<|im_end|>
<|im_start|>assistant
The director of film Young Dr. Kildare was buried in Manhattan, New York.<|endoftext|>
q:
a:<|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
Where was the place of burial of the director of film Young Dr. Kildare?<|im_end|>
<|im_start|>assistant
The director of film Young Dr. Kildare was buried in Manhattan, New York.<|endoftext|>

**Comment by SsmallSong** [comment]
Hello, as mentioned in the Quick Start, you need to change the `--data_path` in the following command to the path of your own dataset (and its content):

```bash
python train/reward_server_qwen_zero.py --data_path data/training_set/stage_2.jsonl --reward_pretrain the_model_path --log_file results/samples/qwen.jsonl --port 1278
